language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
            - cmake

    - os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang++-6
            - cmake

before_install:
  - eval "${MATRIX_EVAL}"

script:
  # Export CC and CXX to tell cmake which compiler to use
  #  - export CC=/usr/bin/gcc-6
  #- export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir build && cd build && cmake .. && make
